version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

defaults: &defaults
  working_directory: ~/arch-scheduler
  docker:
    - image: golang:1.12-stretch

jobs:
  get_source:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - arch-scheduler

  build_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build source
          command: make
      - persist_to_workspace:
          root: ~/
          paths:
            - arch-scheduler/bin

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install linter
          command: make linter-install
      - run:
          name: Run tests
          command: make test
      - codecov/upload:
          file: cover.out

workflows:
  version: 2
  build_and_test:
    jobs:
      - get_source
      - unit_test:
          requires:
            - get_source
      - build_source:
          requires:
            - get_source
