apiVersion: v1
kind: Pod
metadata:
  name: sif-scheduler-extender
spec:
  containers:
    - name: sif-scheduler-extender
      image: cloud.sylabs.io/library/slurm/arch-scheduler
      ports:
        - containerPort: 8888
      env:
        - name: PORT
          value: "8888"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - namespaces:
            - kube-system
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              component: kube-scheduler


