apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/run/kubernetes/scheduler.kubeconfig"
algorithmSource:
  policy:
    file:
      # YAML should be supported
      # https://github.com/kubernetes/kubernetes/issues/75852
      path: "deploy/arch-scheduler-policy.yaml"
