apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-scheduler
        - --config=/etc/kubernetes/scheduler/config.yaml
      image: k8s.gcr.io/kube-scheduler:v1.15.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10251
          scheme: HTTP
        initialDelaySeconds: 15
        timeoutSeconds: 15
      name: kube-scheduler
      resources:
        requests:
          cpu: 100m
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/kubernetes/scheduler
          name: scheduler-config
          readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
    - name: scheduler-config
      configMap:
        name: scheduler-config
        items:
          - key: policy
            path: policy.yaml
          - key: config
            path: config.yaml
