apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - mkfifo /tmp/pipe; (tee -a /var/log/kube-scheduler.log < /tmp/pipe & ) ; exec
          /usr/local/bin/kube-scheduler --config=/var/lib/kube-scheduler/config.yaml --leader-elect=true
          --v=2 > /tmp/pipe 2>&1
      image: k8s.gcr.io/kube-scheduler:v1.13.5
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10251
        initialDelaySeconds: 15
        timeoutSeconds: 15
      name: kube-scheduler
      resources:
        requests:
          cpu: 100m
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/kubernetes/scheduler/config.yaml
          name: scheduler-config
          readOnly: true
        - mountPath: /etc/kubernetes/scheduler/policy.yaml
          name: scheduler-policy
          readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  volumes:
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
    - name: scheduler-config
      hostPath:
        path: /etc/kubernetes/scheduler/config.yaml
        type: File
    - name: scheduler-policy
      hostPath:
        path: /etc/kubernetes/scheduler/policy.yaml
        type: File
